name: Python tests

on: push

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: make install
      - name: Install development dependencies (Pytest and Coverage)
        run: make install-dev
      - name: Execute unit tests with Pytest
        run: make tests
      - name: Analyse coverage report
        run: make report
